### ISSUE TITLE
Change library against pure vanilla js slider to get rid of jquery

### ISSUE THREAD

**Issue by K0NZ1** [heimrichhannot/contao-slick-bundle#1]
https://github.com/ganlanyuan/tiny-slider

**Comment by fritzmg** [comment]
@K0NZ1 this is the contao-__slick__-bundle. It integrates the [slick](http://kenwheeler.github.io/slick/) slider in Contao. The integration _tiny-slider_ would need to happen in another extension ;)

**Comment by fatcrobat** [comment]
@fritzmg You are right, this task is just a roadmap. We would like to get rid of any jQuery dependency, and there will be a tiny-slider-bundle some days.

**Comment by fatcrobat** [comment]
[Tiny-Slider](https://github.com/heimrichhannot/contao-tiny-slider-bundle) implementation based https://github.com/heimrichhannot/contao-encore-bundle done.
