### ISSUE TITLE
Custom element template

### ISSUE THREAD

**Issue by Misco** [heimrichhannot/contao-slick-bundle#11]
Hello,

the Custom element template field is empty for the ce_slick elements.
i would like to use modified templates. Can in this field please showup all ce_slick_ Templates?

Thanks

**Comment by fatcrobat** [comment]
@Misco Should already be possible, copy ce_slick.html to /templates/ce_slick_custom.html5

**Comment by seibtph** [comment]
@fatcrobat This doesn't work for the content slider start element. I have copy ce_slick_content_start.html5, but the custom template field is empty.

I have installed the version 1.2.2 of the slick bundle.
