### ISSUE TITLE
Failed to install 4.7.x

### ISSUE THREAD

**Issue by jankout** [heimrichhannot/contao-slick-bundle#12]
Hello, 

unfortunately I couldn't install your extension because of the restriction of minimum requirements. Could you fix it, please? Thank you. 

![slick failed installation](https://user-images.githubusercontent.com/3715050/56139349-fadd8500-5f98-11e9-8c74-caf205eb9b7d.png)

**Comment by fatcrobat** [comment]
@jankout This module is currently in beta, update your project composer.json to `"minimum-stability": "beta"` if you still want to use this module.
