### ISSUE TITLE
slick.min.js und slick.css werden nicht eingebunden

### ISSUE THREAD

**Issue by sixtmedia** [heimrichhannot/contao-slick-bundle#13]
In meiner Contao 4.4.40 Installation (mit contao-slick-bundle 1.0.0-beta17) werden die Dateien slick.min.js und slick.css nicht eingebunden.

In der contao-slick-bundle/src/Resources/contao/config/config.php wird folgendes versucht einzubinden:
    $GLOBALS['TL_USER_CSS']['slick']                 = 'assets/slick/slick.css|static';
    $GLOBALS['TL_JAVASCRIPT']['slick']               = 'assets/slick/slick.min.js|static';

In meiner Installation (über den Manager) wurde Slick mit den contao-components jedoch unter assets/**slick**/slick (ein Ordner /slick mehr im Pfad) installiert.

Korrekt wäre also:
    $GLOBALS['TL_USER_CSS']['slick']                 = 'assets/slick/slick/slick.css|static';
    $GLOBALS['TL_JAVASCRIPT']['slick']               = 'assets/slick/slick/slick.min.js|static';

Ich musste das ändern um die Erweiterung zum laufen zu bekommen.

So wie ich es einschätze könnte das ein Fehler in der Erweiterung sein und die Pfade müssten angepasst werden.

**Comment by koertho** [comment]
@sixtmedia Das sieht nach einem Fehler in deiner Config aus. Die Pfade stimmen so.

**Comment by sixtmedia** [comment]
Ich habe das in neuen Installationen - bei zwei verschiedenen Hostern - getestet. Neues Contao 4.4 und nur das slick-bundle Modul. Alles über den Contao Manager Installiert.
Sonst nichts verändert. Die Skripte werden in 
assets/slick/slick/slick.css und 
assets/slick/slick/slick.min.js installiert und sind daher nicht eingebunden.

Welche config könnte denn bei mir der Auslöser dafür sein? Ich habe da keine Idee.

Danke
Timon

**Comment by koertho** [comment]
Was steht in deiner composer.json unter extra -> contao-component-dir?
Ansonsten scheint das ein Fehler im Contao Manager zu sein.
