### ISSUE TITLE
Abandoned Packages Hinweis beim Composer Update

### ISSUE THREAD

**Issue by saress** [heimrichhannot/contao-slick-bundle#14]
Hallo,

beim jedem Update über den Contao Manager erhalte ich folgende Meldungen in  Verbindung mit dem contao-slick-bundle:

Package heimrichhannot/contao-ajax is abandoned, you should avoid using it. Use heimrichhannot/contao-ajax-bundle instead.
Package heimrichhannot/contao-multi_column_editor is abandoned, you should avoid using it. Use heimrichhannot/contao-multi-column-editor-bundle instead.
Package heimrichhannot/contao-request is abandoned, you should avoid using it. Use heimrichhannot/contao-request-bundle instead.

Ich habe das in anderem Zusammenhang auch hier im Contao Forum kurz mal gepostet:

https://community.contao.org/de/showthread.php?75341-JS-Fehler-bei-heimrichhannot-contao-slick-bundle&p=507220&viewfull=1#post507220

Das hatte aber mit dem ursprünglichen in dem Post beschriebenen Problem nichts zu tun, sondern eher, dass ich ein falsche Package (dev-master) installiert habe, da mir nicht klar war, dass das bundle noch Beta Status hat.

Beste Grüße
Sares

**Comment by koertho** [comment]
@saress Dieses Bundle hat keinerlei Abhängigkeiten, die abandoned sind. Auch unter den direkten Abhängigkeiten ist da nichts zu sehen. Daher scheinen die Meldungen von einem anderen Bundle zu kommen. 
Ich habe heute übrigens Version 1.0.0 getagt.

**Comment by saress** [comment]
Hallo Koertho,

vielen Dank für den Hinweis, ich habe die Version umgestellt und bislang ist der Fehler nicht mehr aufgetreten, vielen Dank!

Beste Grüße
Sares
