### ISSUE TITLE
Bilderslider: SVGs werden nicht angezeigt

### ISSUE THREAD

**Issue by saress** [heimrichhannot/contao-slick-bundle#15]
Hallo,

ich habe gerade einen Slick Element vom Typ Bilderslider angelegt und bei der Bildauswahl SVGs verwendet. Diese werden allerdings nicht im Frontend angezeigt. Daraufhin habe ich mit der gleichen Konfiguration ganz normale Bilder genommen und auch JPGs und SVGs gemischt.
In beiden Fällen wurden die JPGs angezeigt und die SVGs einfach ignoriert.

Werden SVGs beim Bilderslider nicht unterstützt?
Aktuell läuft: C 4.4.43 LTS und die aktuellste contao-slick-bundle Version 1.0.1. vom 08.08.2019.

Vielen Dank und beste Grüße
Sares

**Comment by koertho** [comment]
@saress Ohne es getestet zu haben: Welchen Browser nutzt du? Werden die SVGs im Quelltext eingebunden?

**Comment by koertho** [comment]
@saress Fehler wurde in version 1.1.1 behoben.

**Comment by saress** [comment]
Hallo Koertho,

sorry, hab gerade erst deine Nachricht gesehen und vielen Dank für die Fehlerbehebung, funktioniert bestens.

Beste Grüße
Sares

**Comment by koertho** [comment]
@saress Kein Problem, danke für das Feedback!
