### ISSUE TITLE
custom.Paging is not a function

### ISSUE THREAD

**Issue by Fipspilot** [heimrichhannot/contao-slick-bundle#18]
Hey,

I found an issue while updating Contao 3.5 to Contao 4.4.

Because the heimrichhannot/contao-slick is "officially" not compatible with the latest Contao 4.4 version I installed the heimrichhannot/contao-slick-bundle.

I use a slider with custom.Paging and in the -bundle version I get an error:

`o.options.customPaging.call is not a function`

When I remove the customPaging option, the Slider works again, just with numbers.

For now I switched back to the heimrichhannot/contao-slick.

It would be nice, if it´ll also work in the -bundle version.

Thanks for all your work!

Regards
Fipspilot

**Comment by koertho** [comment]
Hi, can you please provide how you use the customPaging option? But to be honest: this is a functionality which comes from the library, not from this bundle. Maybe the way how we instantiate slick changes (you can look into the sources, we use webpack encore to compile), but this is the point where you need to adept your code.

**Comment by Fipspilot** [comment]
I load this script in the <head> Tag
`<script>
(function($){
	historyNav = {
		   customPaging : function(slick,i){
			  var label = $(slick.$slides[i]).find("h5").text();
			 return '<button>' + label + '</button>';
  }
};
})(jQuery);
</script>`

In the Slick-Configurator I enter
`historyNav.customPaging`
in the "customPaging" field.

I am just wondering, because it works the same way in heimrichhannot/contao-slick

**Comment by koertho** [comment]
We use the custom Paging function in one project with signon bundle, an it workes well. We use it together with slick event , here the example: 

```
$('body.myPage .slick').on('init', function(slick) {
    let target = $(slick.target);
    let slidesCount = target.find('.slick-slide:not(.slick-cloned)').length;
    let $slickDots = target.find('.slick-dots');
    updateSlickDots($slickDots, 1, slidesCount);
    target.on('beforeChange', (event, slick, currentSlide, nextSlide) => {
        updateSlickDots($slickDots, nextSlide+1, slidesCount);
    });
});
```

**Comment by cmartin6** [comment]
@Fipspilot did you manage to get this to work? I am having the same issue...
