### ISSUE TITLE
Einstellungsdialog "responsive" Darstellungsfehler im Backend

### ISSUE THREAD

**Issue by saress** [heimrichhannot/contao-slick-bundle#19]
Hallo, 

beim Bereich "responsive" gibt es einen Umbruch, eventuell fehlen hier die entsprechenden Language-Einträge, siehe Screenshot.

![slick-slider-config](https://user-images.githubusercontent.com/1481301/68271395-9c751280-0060-11ea-9270-47704e04f4bc.jpg)

Contao 4.4.5 und die letzte Version contao-slick-bundle Version 1.2.2.

Beste Grüße und vielen Dank,
Saress

**Comment by koertho** [comment]
Hi, sorry for the late response. Fixed in 1.3.0.

**Comment by saress** [comment]
Kein Problem, sind ja doch einige Erweiterung, die Ihr da immer im Blick haben müsst. Vielen Dank jedenfalls für das Update!

Beste Grüße
Saress
