### ISSUE TITLE
slick_appendArrows option missing

### ISSUE THREAD

**Issue by hmaerk** [heimrichhannot/contao-slick-bundle#24]
Hi there,
I am tried to render the navigation elements in a particular div on my page. But I can´t seem to find the right option. In your documentation "appendArrows" would be the correct one. In system->slick config -> [my global template] the option "appendArrows" is missing. 

![grafik](https://user-images.githubusercontent.com/64426433/80393993-87f83100-88b1-11ea-997d-3f745fc789be.png)

I am using Contao v4.9.2 with heimrichhannot/contao-slick-bundle v1.4.1.

I´ve had a look into the code and found, that it is not definied:
contao-slick-bundle-master\src\Resources\contao\dca\tl_slick_spread.php Line 194-214:
```
        'slick_adaptiveHeight'   => [
            'label'     => &$GLOBALS['TL_LANG']['tl_slick_spread']['slick_adaptiveHeight'],
            'inputType' => 'checkbox',
            'exclude'   => true,
            'eval'      => [
                'tl_class' => 'w50',
            ],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        //		slick_appendArrows,
        //		slick_appendDots,
        'slick_arrows'           => [
            'label'     => &$GLOBALS['TL_LANG']['tl_slick_spread']['slick_arrows'],
            'inputType' => 'checkbox',
            'exclude'   => true,
            'default'   => true,
            'eval'      => [
                'tl_class' => 'w50',
            ],
            'sql'       => "char(1) NOT NULL default ''",
        ],
```
but translations seem to be defined:
contao-slick-bundle-master\src\Resources\contao\languages\de\tl_slick_spread.php Line 31:
```
    $GLOBALS['TL_LANG']['tl_slick_spread']['slick_appendArrows'] = ['appendArrows', 'Stelle ändern, an der die Navigations-Pfeile angehangt werden (Selektor, htmlString, Array, Element, jQuery-Objekt). Standard: $(element)'];
```

**Comment by koertho** [comment]
Hi, I don't know why this field isn't there anymore (this was before my time), but the easiest and best way would be to use the huh.slick.beforeInit Javascript event. Just add this option to the options object and it should work.

**Comment by hmaerk** [comment]
Thanks for the fast reply. I´ll try it that way :)
