### ISSUE TITLE
Problem when used togehter with lightboxes?

### ISSUE THREAD

**Issue by christianbargon** [heimrichhannot/contao-slick-bundle#25]
Dear heimrichhannot,

we used your slick-bundle for the first time - we really liked it!
We have an issue together with the use of "colorbox/lightbox" in Contao.
When we open News-Details twice or three times the browser crashes - in the code we noticed that all "not-displayed" elements were duplicated after we opened another News. You have to close these copies, too and after 2 or three times... crash... 

You can test it by yourself on the page: http://haf.c4.bargon.net

Maybe it is a bug in slick or "our own fault"

Regards Chris

**Comment by koertho** [comment]
@christianbargon Sorry for the late reply. I can't find any error, there is no browser crash for me and no wrong duplicated element (slick is duplicating elements, but thats normal). Also we are not responsible for slick itself, just for the contao integration ;)
I'm sorry I can't help you as I can't find any problem.
