### ISSUE TITLE
JS-Fehler Contao 4.9.3

### ISSUE THREAD

**Issue by seibtph** [heimrichhannot/contao-slick-bundle#27]
Leider bekomme ich den Slider in der Contao 4.9.3 nicht zum Laufen.

Fehlermeldung:

contao-slick-bundle.js?v=57307ebf:1 Uncaught TypeError: $ is not a function
    at Function.value (contao-slick-bundle.js?v=57307ebf:1)
    at contao-slick-bundle.js?v=57307ebf:1
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.value (contao-slick-bundle.js?v=57307ebf:1)

Leider weiß ich nicht genau wie ich das lösen kann.

**Comment by koertho** [comment]
Hi, jQuery hast du im Layout aktiviert und wird auch im Quellcode darüber eingebunden?

**Comment by seibtph** [comment]
@koertho 

Sorry, dass die Antwort so lange gedauert hat. 

jQuery ist eingebunden. Den gleichen Fehler hatte ich eben auch unter Contao 4.4 mit der aktuellsten Modulversion (1.4.4). Jetzt bin ich zur Version 1.2.2 gewechselt, weil ich wusste, dass es da auf jeden Fall noch ging und da funktioniert es tatsächlich ohne Probleme.

**Comment by koertho** [comment]
Mhm, bekomme den Fehler leider nicht reproduziert. Liegt es eventuell am Browser? Welchen nutzt du?
`Uncaught TypeError: $ is not a function` klingt für mich eben wie jQuery nicht richtig eingebunden. Du könntest eventuell mal testen, ob die $ variable im windows object belegt ist, indem du in den Dev-Tools in die Konsole einfach $ ausführst und schaust, was zurück kommt.
