### ISSUE TITLE
Nachrichten - Fehler bei "Galerie hinzufügen"

### ISSUE THREAD

**Issue by s-worx** [heimrichhannot/contao-slick-bundle#28]
Bei den Nachrichteneinstellungen (Contao 4.9.3 ) gibt es den Punkt Galerie hinzufügen. Sobald diese Option gewählt wird läuft das System in ein Timeout und bei neuem Aufruf der Einstellungen kommt folgende Fehlermeldung.
Fehler kann man nur wieder behebn wenn man direkt in der Datenbank der tl_news die Option addGallery wieder entfernt.

Attempted to call an undefined method named "getElementTemplates" of class "tl_content". Did you mean to call "getTinyTemplates"?

Ich hatte vor einiger Zeit den gleichen Fehler bei einem eigenen Modul.
https://community.contao.org/de/showthread.php?77183-Contao-update-von-4-7-auf-4-9&p=519593#post519593

**Comment by koertho** [comment]
Shoud be fixed in 1.4.3
