### ISSUE TITLE
Invalide Option randomActive

### ISSUE THREAD

**Issue by Misco** [heimrichhannot/contao-slick-bundle#30]
Hallo,

ich nutze Contao 4.4
Im data steht zwar "randomActive":true, aber ohne Wirkung.

Grüße
Dennis

**Comment by koertho** [comment]
@Misco Hi, ich habe gerade mal geschaut und die Option gibt es in Slick gar nicht, ist wohl ein Überbleibsel aus Urzeiten. Werden wir bei Gelegenheit mal entfernen. Falls du eine Zufallsfunktion benötigst, schau mal hier: https://stackoverflow.com/questions/49950262/random-slide-order-in-slick-image-slider/49950398

**Comment by Misco** [comment]
Danke für den Link. 
Evtl. kann man es auch wieder hier mit Funktion füllen:
mit php prüfen ob Zufall angehackt ist und dann (in etwa):

`$("slick").on("init reInit", function() {
      var i = $('.slick-slide').length;
      var initalSlide = $("slick").attr("random") ? Math.floor(Math.random() * i) : 0;
      $("slick").slick('slickGoTo', initalSlide);
  });`

**Comment by koertho** [comment]
@Misco Du darfst gern einen Pull-Request machen. Wir werden es nicht implementieren, da Slick nicht mehr unser Haupt-Slider ist und wir eine solche Funktion bisher nicht benötigen.

**Comment by Misco** [comment]
ok, welchen Slider verwendetet ihr jetzt?

**Comment by koertho** [comment]
[Tiny Slider](https://github.com/heimrichhannot/contao-tiny-slider-bundle), ist ohne jQuery.

**Comment by koertho** [comment]
Ich habe gerade mal geschaut, im slick modul war diese Funktion tatsächlich funktional. Aber im Bundle hat dies wohl noch nie funktioniert und wir werden das auch nicht nachziehen. Wie gesagt, das Bundle ist ja erweiterbar gebaut, ist also sehr einfach nachrüstbar. In Version 1.5.0 habe ich die entsprechende Konfiguration nun entfernt.
