### ISSUE TITLE
Compile Error: Cannot declare class tl_slick_spread 

### ISSUE THREAD

**Issue by herrrilke** [heimrichhannot/contao-slick-bundle#32]
**Context**
Contao version: 4.9.10
Bundle version: 1.4 und 1.5
PHP version: 7.4

**Description**
auf der console bekomme ich beim update auf C4.9.10 den fehler

"Compile Error: Cannot declare class tl_slick_spread, because the name is already in use" 

die ganze ausgabe ist [hier im contao-forum](https://community.contao.org/de/showthread.php?79983-Console-Compile-Error-Cannot-declare-class-tl_slick_spread&p=538013#post538013) beschrieben.

spooky war der meinung, dass der fehler mit [diesen einträge in der composer.json](https://github.com/heimrichhannot/contao-slick-bundle/blob/a7f4e517b1b6b7993f1f2d584b13fac9bc43fd97/composer.json#L40-L49) zusammenhängen.

viele grüße

karsten

**Comment by herrrilke** [comment]
mmh: 
ich glaube es liegt eher daran, dass in der installation noch eine altes slick modul unter `system/modules/slick` lag. daher dann auch die meldung _name is already in use_
sorry. 
melde mich als honk ab ;)

**Comment by fritzmg** [comment]
Then you should close this issue ;)

**Comment by koertho** [comment]
Ja, das composer-plugin spielt so manchen Streich ;) 

Den Eintrag in der composer.json entferne ich mal bei Gelegenheit, danke für den Hinweiß!
