### ISSUE TITLE
Content Slider Navigation

### ISSUE THREAD

**Issue by seibtph** [heimrichhannot/contao-slick-bundle#35]
**Context**
Contao version: 4.9.12
Bundle version: 1.5.0
PHP version: 7.4

**Description**

Beim Anlegen des Elements Content-Slider-Navigation Element gibt es einen Fehler:

`Class HeimrichHannot\SlickBundle\Element\ContentSlickNavSlideSeparator does not exist`

**Comment by koertho** [comment]
Hi, sorry for the very late answer. We're not very busy on this bundle as we've moved to tiny slider. I looked into this issue and found, that this problem must have already exist in the old slick module and I think this content element was never used. The class does not exist, so I deleted the content element entry. If you need something like this, you're welcome to do a PR or become a maintainer of this bundle.
