### ISSUE TITLE
Lightbox Gallery & slick-cloned

### ISSUE THREAD

**Issue by cmichael-de** [heimrichhannot/contao-slick-bundle#43]
Beim verwenden des Slick Content Elementes im Zusammenhang mit der Lightbox Gallery verdoppeln sich die Lightbox Gallery Bilder, die man beim öffnen der Lightbox durchklicken kann. Ursache ist das Attribut data-lightbox="irgendEineID". Bei geklonten Content Elemente wird data-lightbox="irgendEineID" auch eins zu eins mitgeklont. 

Ist es möglich das Klonen optional zu unterbinden?

**Comment by koertho** [comment]
Puh, das ist eine schwierige Kombination und ich wüsste nicht, wie das gehen sollte. Am besten die Dokumentation von Slick (http://kenwheeler.github.io/slick/) dort durchforsten oder bei Github dann die Issues, da findet man häufig was. Das sollte ja nichts mit unserem Bundle zu tun haben.
