### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by callmesupercookie** [heimrichhannot/contao-slick-bundle#45]
**Context**
Contao version: 4.11.5
Bundle version: 1.5.0
PHP version: 7.4

Since updating Contao the slick plugin throws me a js error:
```
Uncaught TypeError: $ is not a function
    at Function.value (jquery.min.js,jquery.touchSwipe.min.js,contao-utils-bundle.js,jq...-9e129a90.js:598)
    at jquery.min.js,jquery.touchSwipe.min.js,contao-utils-bundle.js,jq...-9e129a90.js:598
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.value (jquery.min.js,jquery.touchSwipe.min.js,contao-utils-bundle.js,jq...-9e129a90.js:598)
```

`var a = $(n).closest(".collapse");`

Can someone help?

**Comment by koertho** [comment]
Looks live you haven't jquery on your page (or it's loaded after the slick script).

**Comment by callmesupercookie** [comment]
We import jQuery in the Page Layout. Worked before and it's still getting imported. Can't figure out what changed with the update.

**Comment by koertho** [comment]
Please check if the jquery script is loaded before the slick script in the page source code and if the jquery-script promotes the window object properly (window.jquery and window.$).
Which bundle version was installed before?
