### ISSUE TITLE
Contao 4.11 broken after installation

### ISSUE THREAD

**Issue by bohnmedia** [heimrichhannot/contao-slick-bundle#46]
**Context**
Contao version: 4.11.5
Bundle version: 1.5.0
PHP version: 7.4.18

**Description**

Here is what i did:
1. Downloaded contao-manager.phar to /web directory and renamed the file to contao-manager.phar.php.
2. Installed a mimimal contao 4.11 version with contao manager.
3. Updated the database.
4. Selected bundle "heimrichhannot/contao-slick-bundle" for installation in contao manager.
5. Checked update for contao too, because otherwise installation failed.
6. Installed the package.

When I tried to open the install tool again, I got the following error message.

> **ClassNotFoundError**
> Attempted to load interface "ServiceSubscriberInterface" from namespace "Symfony\Component\DependencyInjection".
Did you forget a "use" statement for "Symfony\Contracts\Service\ServiceSubscriberInterface"?

After changing "use Symfony\Component\DependencyInjection\ServiceSubscriberInterface" to "use Symfony\Contracts\Service\ServiceSubscriberInterface" in /vendor/heimrichhannot/contao-utils-bundle/src/Util/Utils.php the error message disappeared.

**Comment by koertho** [comment]
@bohnmedia Hi, that's an already known issue of our utils bundle which I will fix soon. Stay tuned :)

**Comment by koertho** [comment]
Should be fixed in Utils Bundle 2.196.1. But keep in mind, our symfony 5 support should be considerent experimental, as we only use contao 4.9 with symfony 4.

**Comment by bohnmedia** [comment]
Thank you! Tested and worked. :)
