### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by Kabathus** [heimrichhannot/contao-slick-bundle#55]
**Context**
Contao version: 4.12 / 4.13
Bundle version:  1.6.0
PHP version: 8.0 / 8.1

**When refreshing the prod cache, there are the following PHP warnings:**

` // Warming up the cache for the prod environment with debug                     // false                                                                       

PHP Warning:  Undefined array key "orderSRC" in <pfad>/web/vendor/heimrichhannot/contao-slick-bundle/src/EventListener/HookListener.php on line 209
PHP Warning:  Undefined array key "slick-content-start" in <pfad>/web/vendor/heimrichhannot/contao-slick-bundle/src/EventListener/HookListener.php on line 118
PHP Warning:  Undefined array key "slick-content-start" in <pfad>/web/vendor/heimrichhannot/contao-slick-bundle/src/EventListener/HookListener.php on line 177
PHP Warning:  Undefined array key "__selector__" in <pfad>/web/vendor/heimrichhannot/contao-slick-bundle/src/EventListener/HookListener.php on line 149
PHP Warning:  Undefined array key "subpalettes" in <pfad>/web/vendor/heimrichhannot/contao-slick-bundle/src/EventListener/HookListener.php on line 155
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   

# Process terminated with exit code 0
# Result: OK`

**Comment by koertho** [comment]
Should be fixed in 1.6.1
