### ISSUE TITLE
Slick Slider with thumbnails

### ISSUE THREAD

**Issue by pixelmatty** [heimrichhannot/contao-slick-bundle#63]
Dear community

I use latest Contao 4.9 with latest Slick Bundle. Has anyone already used it with thumbnails and built a template for this? Means one image and below (or beside) the thumbnails of all pictures of the slider? There is an examples at stackoverflow but I'm not able to transform this for use with the Contao Slick extension. I suppose a template and some formatting css for thumbnail selectors are the way? What do I have to change in contao or to add in template ...? 

[https://stackoverflow.com/questions/39567327/how-to-create-thumbnail-carousel-with-image-previews-in-slick-js](url)

I would appreciate some help.
Thanks
Pixelmatty

**Comment by koertho** [comment]
You could create a complete custom template and add the code there, no need for the bundle itself (just for the scripts).

**Comment by pixelmatty** [comment]
Ok, thanks, but this is my problem and why I asked for an existing template. Sorry, but I don't know how the template and the additional code has to look like. I don't understand enough from coding. I'm a Designer and want to use it for my privat website.

**Comment by pixelmatty** [comment]
Slick default template:

`<?php foreach ($this->body as $item): ?>
    <?php if ($item->addImage): ?>
        <div>
            <figure class="image_container"<?php if ($item->margin): ?> style="<?php echo $item->margin; ?>"<?php endif; ?>>
                <?php if ($item->href ?? false): ?>
                    <a href="<?php echo $item->href; ?>"<?php echo $item->attributes; ?> title="<?php echo $item->alt; ?>">
                        <?php $this->insert('picture_default', $item->picture); ?>
                    </a>
                <?php else: ?>
                    <?php $this->insert('picture_default', $item->picture); ?>
                <?php endif; ?>
                <?php if ($item->caption): ?>
                    <figcaption class="caption" style="width:<?php echo $item->arrSize[0]; ?>px"><?php echo $item->caption; ?></figcaption>
                <?php endif; ?>
            </figure>
        </div>
    <?php endif; ?>
<?php endforeach; ?>`

**Comment by koertho** [comment]
Sorry, I can't teach you the basics here. Have a look at the documentation: https://docs.contao.org/dev/framework/templates/

Then you can create a custom template for the ce_html element (for example, in 4.13 you also have a simple template element).
You also need to load the assets in there, as slick bundle loads them only when needed:
```
<?php 
$GLOBALS['TL_USER_CSS']['slick']                 = 'assets/slick/slick/slick.css|static';
$GLOBALS['TL_JAVASCRIPT']['slick']               = 'assets/slick/slick/slick.min.js|static';`
?>

**Comment by pixelmatty** [comment]
OK thanks so far. I'll try to check it out. 
But nevertheless I wonder why no one has already used it. Or are not so many users in here?

**Comment by koertho** [comment]
I close this since this is not direct issue with this bundle.
