### ISSUE TITLE
current bundle it´s not possible to install with contao manager

### ISSUE THREAD

**Issue by zonky2** [heimrichhannot/contao-slick-bundle#7]
current bundle it´s not possible to install with contao manager

**Comment by tuxenberger** [comment]
Same here.

**Comment by fatcrobat** [comment]
Contao version?

**Comment by tuxenberger** [comment]
Contao Manager 1.1.3, Contao 4.4.34, PHP 7.2, 

Massage form Contao Manager "Console task terminated!
The background task has stopped unexpectedly. Please check the console protocol."

Where can i find the protocol to get more info for you? Is it /system/logs ?

**Comment by tuxenberger** [comment]
Tested localy and on Hosting Server (novatrend.ch)

**Comment by fatcrobat** [comment]
Please add the content of the error message from the /var/logs/prod-date....log file

**Comment by tuxenberger** [comment]
On local development:

[2019-02-27 03:16:52] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_url_fragment":"contao-manager/users.json","_route":"contao_catch_all"},"request_uri":"http://my_local_sitefolder.loc/contao-manager/users.json","method":"HEAD"} []
[2019-02-27 03:16:52] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2019-02-27 03:16:52] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_url_fragment":"contao-manager/users.json","_route":"contao_catch_all"},"request_uri":"http://my_local_sitefolder.loc/contao-manager/users.json","method":"GET"} []
[2019-02-27 03:16:52] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2019-02-27 03:16:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://my_local_sitefolder.loc/contao-manager/users.json" at /Users/my_user_account/Sites/my_local_sitefolder/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: http://my_local_sitefolder.loc/contao-manager/users.json at /Users/my_user_account/Sites/my_local_sitefolder/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: http://my_local_sitefolder.loc/contao-manager/users.json at /Users/my_user_account/Sites/my_local_sitefolder/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:64)"} []

**Comment by tuxenberger** [comment]
on novatrend.ch

No logfile createted :-/

**Comment by fatcrobat** [comment]
Cant find any slick related errors.:/ hard to debug without any clue.

**Comment by HendrikBengs** [comment]
I have the same problem. Contao 4.4.35 | PHP 7.3.2.

The Contao-Manager stopped unexpectedly with the following message:

> In InitCommand.php line 737:
>                                                                                
>   Could not find a version of package heimrichhannot/contao-slick-bundle matc  
>   hing your minimum-stability (stable). Require it with an explicit version c  
>   onstraint allowing its desired stability.          

I hope this information will help you?

**Comment by koertho** [comment]
@HendrikBengs Maybe you need to set `"minimum-stability": "dev"` in your composer.json, due this bundle is still beta.

**Comment by Misco** [comment]
i get this error:

`> Resolving dependencies using Composer Cloud v2.0.6

[364.8MiB/7.32s] Loading composer repositories with package information
[365.1MiB/7.40s] Updating dependencies
[2673.1MiB/98.43s] Your requirements could not be resolved to an installable set of packages.
[2673.1MiB/98.44s] 
  Problem 1
    - Conclusion: don't install symfony/symfony 4.1.x-dev
    - Conclusion: don't install symfony/framework-bundle 3.4.x-dev
    - Conclusion: don't install contao/conflicts dev-master
    - symfony/symfony v3.4.7 conflicts with contao/conflicts[dev-master].
    - symfony/symfony v3.4.11 conflicts with contao/conflicts[dev-master].
    - symfony/symfony v3.4.8 conflicts with contao/conflicts[dev-master].
    - Installation request for contao/conflicts *@dev -> satisfiable by contao/conflicts[dev-master].
    - Installation request for symfony/var-dumper (locked at v4.2.3) -> satisfiable by symfony/var-dumper[v4.2.3].
    - Conclusion: don't install friendsofsymfony/http-cache-bundle 2.6.1|install symfony/symfony v3.4.11|install symfony/symfony v3.4.7|install symfony/symfony v3.4.8
    - symfony/symfony v3.4.0 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.0-BETA1 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.0-BETA2 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.0-BETA3 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.0-BETA4 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.0-RC1 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.0-RC2 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.1 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.2 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - symfony/symfony v3.4.3 conflicts with friendsofsymfony/http-cache-bundle[2.6.1].
    - Installation request for friendsofsymfony/http-cache-bundle (locked at 2.6.1) -> satisfiable by friendsofsymfony/http-cache-bundle[2.6.1].
    - Installation request for symfony/twig-bundle (locked at 4.1.x-dev) -> satisfiable by symfony/symfony[4.1.x-dev], symfony/twig-bundle[4.1.x-dev].
    - Conclusion: don't install symfony/asset 4.1.x-dev|install symfony/symfony v3.4.0|install symfony/symfony v3.4.0-BETA1|install symfony/symfony v3.4.0-BETA2|install symfony/symfony v3.4.0-BETA3|install symfony/symfony v3.4.0-BETA4|install symfony/symfony v3.4.0-RC1|install symfony/symfony v3.4.0-RC2|install symfony/symfony v3.4.1|install symfony/symfony v3.4.11|install symfony/symfony v3.4.2|install symfony/symfony v3.4.3|install symfony/symfony v3.4.7|install symfony/symfony v3.4.8
    - don't install symfony/symfony 3.4.x-dev|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.10|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.12|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.13|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.14|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.15|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.16|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.17|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.18|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.19|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.20|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.21|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.22|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.23|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.4|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.5|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.6|don't install symfony/asset 4.1.x-dev
    - don't install symfony/symfony v3.4.9|don't install symfony/asset 4.1.x-dev
    - Installation request for symfony/asset (locked at 4.1.x-dev) -> satisfiable by symfony/asset[4.1.x-dev], symfony/symfony[4.1.x-dev].
    - Installation request for heimrichhannot/contao-slick-bundle dev-master -> satisfiable by heimrichhannot/contao-slick-bundle[dev-master].
    - Installation request for symfony/framework-bundle (locked at 4.1.x-dev) -> satisfiable by symfony/framework-bundle[4.1.x-dev], symfony/symfony[4.1.x-dev].
    - Conclusion: install symfony/symfony 3.4.x-dev|install symfony/symfony 4.1.x-dev|install symfony/symfony v3.4.0|install symfony/symfony v3.4.0-BETA1|install symfony/symfony v3.4.0-BETA2|install symfony/symfony v3.4.0-BETA3|install symfony/symfony v3.4.0-BETA4|install symfony/symfony v3.4.0-RC1|install symfony/symfony v3.4.0-RC2|install symfony/symfony v3.4.1|install symfony/symfony v3.4.10|install symfony/symfony v3.4.11|install symfony/symfony v3.4.12|install symfony/symfony v3.4.13|install symfony/symfony v3.4.14|install symfony/symfony v3.4.15|install symfony/symfony v3.4.16|install symfony/symfony v3.4.17|install symfony/symfony v3.4.18|install symfony/symfony v3.4.19|install symfony/symfony v3.4.2|install symfony/symfony v3.4.20|install symfony/symfony v3.4.21|install symfony/symfony v3.4.22|install symfony/symfony v3.4.23|install symfony/symfony v3.4.3|install symfony/symfony v3.4.4|install symfony/symfony v3.4.5|install symfony/symfony v3.4.6|install symfony/symfony v3.4.7|install symfony/symfony v3.4.8|install symfony/symfony v3.4.9|install symfony/framework-bundle 3.4.x-dev

[2673.1MiB/98.45s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[760.9MiB/118.38s] Memory usage: 760.89MB (peak: 2677.61MB), time: 118.38s.
[760.9MiB/118.39s] Finished Composer Cloud resolving.
`

**Comment by koertho** [comment]
@Misco Can't see any Slick-Bundle related error here. Maybe you need to set minimum stability to dev in your composer.json?

**Comment by Misco** [comment]
@koertho I did this already. before install was not possible at all. Other Extensions worked well to install.
Its a Contao 4.6
How about to remove all Contao Requeriments. Its beta, so let it be testet on any Contao =)

Just to be sure, i use this in Contao Manager:
heimrichhannot/contao-slick-bundle
Slick, a content slider for contao.More
LGPL-3.0-or-later839 Downloads

Thanks for your work. Its such a nice and useful Slider modul.

**Comment by koertho** [comment]
@Misco No, we can't remove the most important dependency.

Maybe the problem was the ajax bundle, which hat symfony/framework-bundle as dependency. I just release a new version (1.0.7), so please report back, if it now works.

**Comment by Misco** [comment]
@koertho great the install worked now, thank you
