### ISSUE TITLE
responsive-breakpoints option fires javascript-console-error

### ISSUE THREAD

**Issue by cmartin6** [heimrichhannot/contao-slick-bundle#72]
**Context**
Contao version: 4.13.18
Bundle version: 1.8.2
PHP version: 8.1

**Description**
If I use the reponsive-breakpoints option I am getting the following javascript-console-error:
```
VM7268:1 Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 2765
    at JSON.parse (<anonymous>)
    at Function.value (jquery.min.js,contao-utils-bundle.js,slick.min.js,contao-slick-b...-37dec1d9.js:7:1910)
    at jquery.min.js,contao-utils-bundle.js,slick.min.js,contao-slick-b...-37dec1d9.js:7:1679
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.value (jquery.min.js,contao-utils-bundle.js,slick.min.js,contao-slick-b...-37dec1d9.js:7:1656)
```

**Comment by cmartin6** [comment]
?

**Comment by koertho** [comment]
Was it your intention to close this issue?

**Comment by cmartin6** [comment]
I recognized it is not an bundle-issue. I filled the prev- & next-button with inserttags, which results in invalid json ;-)

**Comment by koertho** [comment]
Ok thanks. Next time a little comment would be when closing an issue ;)
