### ISSUE TITLE
Contao 5 Support

### ISSUE THREAD

**Issue by simonla82** [heimrichhannot/contao-slick-bundle#74]
Is support for Contao version 5 planned in the foreseeable future?

**Comment by koertho** [comment]
I want to quote the first lines of the readme:

> We moved away from slick slider to tiny slider (see https://github.com/heimrichhannot/contao-tiny-slider-bundle) because it doesn't have a dependency to jQuery. We're currently looking for a successor for maintaining the bundle. If you're interested, don't hesitate to contact us via GitHub issue or mail.

Beside that, we only use lts versions of contao so therefor we currently do not pull many affords to port our bundles to contao 5. Pull request are welcome.

**Comment by koertho** [comment]
Fixed in 1.9.0
