### ISSUE TITLE
Module slick_eventlist

### ISSUE THREAD

**Issue by digitalingenieur** [heimrichhannot/contao-slick-bundle#8]
There is an issue with palette loading in module slick_eventlist in the backend. Only one field get loaded.
I just tried in a new contao managed installation (4.6.10) with the only extension contao-slick-bundle.
(Same problem with contao-slick under contao 4.4)

slick_newslist works perfectly.

Can anybody of you reproduce this?

![image](https://user-images.githubusercontent.com/13146301/49808369-ad3bdc00-fd5c-11e8-8665-84428b8b20d9.png)

**Comment by digitalingenieur** [comment]
It's an autoloading problem. I just added the CalenderBundle in ContaoManager/Plugin.php in the setLoadAfterStatement. Worked perfectly for me. But I don't know what happens if a user don't use the CalendarBundle at all. Does it have any impact?

**Comment by koertho** [comment]
@digitalingenieur I've updated the Plugin class with CalendarBundle und added the contao-calendar-bundle to the composer depencies, so there should be no problem with autoloading.
