### ISSUE TITLE
Bilder-Slider not using the Contao image size

### ISSUE THREAD

**Issue by vielsaitig** [heimrichhannot/contao-slick-bundle#81]
**Context**
Contao version: 4.13.39
Bundle version: 1.9.2
PHP version: 8.3

**Description**
The image slider "Bilder-Slider" is displaying the full image size of the original file. No matter the settings for the image size. So the Contao image size is not working in the Slick image slider (Bilder-Slider).

**Comment by koertho** [comment]
Fixed in 1.9.3. Thanks for reporting!
