### ISSUE TITLE
contao-slick-bundle.min.js wird nicht eingebunden

### ISSUE THREAD

**Issue by seibtph** [heimrichhannot/contao-slick-bundle#9]
Die Datei contao-slick-bundle.min.js wird unter Contao 4.7 nicht eingebunden, wodurch der Slick Slider bei mir nicht funktionierte.

**Comment by koertho** [comment]
@seibtph Kannst du mehr Kontext geben? Bspw. welche Url Contao aufrufen möchte und wo die js-Datei dann tatsächlich liegt? Wir setzen nur Contao 4.4 sein.

**Comment by jankout** [comment]
Ich habe dasselbe Problem. Kein Script wird angebunden. Gerne schicke ich euch den Link über einen anderen Weg.

**Comment by koertho** [comment]
@seibtph /   @jankout Das scheint ein Bug in Contao 4.7 zu sein. Ich habe es gerade als Issue dort gemeldet: https://github.com/contao/contao/issues/446

Als temporären workaround könntet ihr im folgenden Code `if (\Contao\System::getContainer()->get('huh.utils.container')->isFrontend()) {` durch `if (TL_MODE === 'FE') {` ersetzen:

https://github.com/heimrichhannot/contao-slick-bundle/blob/5f1b4cc4cc8fc07f395db7140018b87cb071ac9e/src/Resources/contao/config/config.php#L90

**Comment by koertho** [comment]
@seibtph @jankout Leider wurde mein Issue vom Core-Team abgelehnt. Ich habe es daher wieder auf die Konstante umgebaut. Solle nun in Version 1.0.0 behoben sein. Bitte gebt kurz Rückmeldung.

Nur zur Info: Wir selbst setzen Slick-Slider nicht mehr in neuen Projekten ein, sondern nutzen den [tiny slider](https://github.com/heimrichhannot/contao-tiny-slider-bundle).

**Comment by koertho** [comment]
@WebBgl Welche Version setzt du ein? Ein Contao-Update dürfte keine Verbesserung bringen.

Zur Info: Ich arbeite gerade an Version 1.1, damit sollte es dann funktionieren.

**Comment by jankout** [comment]
> @WebBgl Welche Version setzt du ein? Ein Contao-Update dürfte keine Verbesserung bringen.
> 
> Zur Info: Ich arbeite gerade an Version 1.1, damit sollte es dann funktionieren.

Das ist super. Vielen Dank dafür! Es scheint, dass der ursprüngliche Entwickler nicht mehr Zeit hat - ich hoffe, dass es ihm nichts ernsthaftes zugestoßen ist.

**Comment by koertho** [comment]
@jankout Manchmal werden solche Libraries eben nicht weiterentwickelt. Wir nutzen daher jetzt den Tiny-Slider, welcher auch ohne jQuery auskommt: https://github.com/heimrichhannot/contao-tiny-slider-bundle (funktioniert auch ohne encore, readme wurde nicht angepasst )

**Comment by koertho** [comment]
@seibtph , @jankout , @WebBgl Der Fehler sollte mit Version 1.1 nun nicht mehr auftreten. Könnt ihr das bestätigen?
